### PR TITLE
Fixed existing filter strings not resetting when a Dash callback changes the dataset displayed in the dash-table.

### PR DESCRIPTION
**Pull request by ucg8j**

### CODE REVIEW

**Comment by ucg8j** [comment]
@chriddyp - the new commit `Fixing bug min_height - 3cc9770` should fix the min_height issues. I've just tested it myself.

**Comment by gennadyi** [comment]
@chriddyp - when is version 0.5.5 going to be available? I'd like to test and use the min_height fix.

**Comment by ucg8j** [comment]
@gennadyi if you wanted to test it before it's merged you could do the following
```
pip install -e git+https://github.com/Acrotrend/tmp-dash-table-exp.git@29d3ef66f0a1fe27422594fadfe14f8f475e9f78#egg=dash_table_experiments
```

**Comment by gennadyi** [comment]
Thanks @ucg8j and @RenzoDS ! 
Just tested the min_height fix in the temp-dash-table-exp, works for my test case now.
Will be happy to have this fix in!

**Comment by gennadyi** [comment]
@ucg8j - I am further testing the table with the 0.5.5 build from your link, and want to report that filter rows doesn't work for me now. 
On my table i click filter rows, input my value and filter box disappears table unchanged. When i got back to 0.5.4 filter rows works (and min_height doesn't as before)

so 0.5.4 -- filter rows ok.                     min_height doesn't work.
so 0.5.5 -- filter rows doesn't work.    min_height ok.

Not sure I need to be on any specific versions of other packages to test 0.5.5 or if this is a real regression bug.

**Comment by ucg8j** [comment]
@gennadyi - would you be able to clarify _in what way_ it is not working. I've just tried it myself see gif below (you might need to open it in a new tab if it is too small):
filter_seems_to_work

**Comment by chriddyp** [comment]
I've finally added integration and screenshot tests in #46 . Could we rebase this branch off of master and then add tests? I can help out with the filter test if you need some help navigating selenium. To test the `min_height` functionality we just need to add a few more examples in https://github.com/plotly/dash-table-experiments/blob/master/test/test_integration.py#L128-L132. The test will take a screenshot of the app (https://github.com/plotly/dash-table-experiments/blob/0e625dd128222cad85ce4e7f14ce8095aa9d13b1/test/test_integration.py#L149) and we'll manually verify that this screenshot is correct.

**Comment by gennadyi** [comment]
@ucg8j - What happens for me is that the filter box row disappears as if I hit filter row button again (and the rows updated callback is fired)  at the entry of first character into any filter box in the row.

**Comment by andreabotti** [comment]
Hi, I have the same feedback as @gennadyi :
0.5.4 -- filter rows ok. min_height doesn't work.
0.5.5 -- filter rows doesn't work. min_height ok.

**Comment by chriddyp** [comment]
I'm fixing the height issues in https://github.com/plotly/dash-table-experiments/pull/50. Let's open up a separate PR with tests for the filtering fixes.

**Pull request closed without merging**
