### PR TITLE
Fixes UI issue where number of rows equals 1 and Filter is selected

### PR DESCRIPTION
**Pull request by ucg8j**

### CODE REVIEW

**Comment by chriddyp** [comment]
great thanks @ucg8j and @RenzoDS !

**Comment by gennadyi** [comment]
I still can't make the table display more than 9 visible rows. Maybe I am missing something if so can someone please give example of how this is possible.

Check the code for getMinHeight() and how it uses constant "10".
my suggestion is 10 should be made into a configurable new parameter to DataTable something like num_visible_rows.

not really interchangeable with how min_height is used.

**Comment by ucg8j** [comment]
@gennadyi this fix is specifically addressing the div resize of the table when the number of rows is so small (1 row) that when the `Filter` button is selected the underlying row is hidden. I'd see this more of a UI bug fix.

From my understanding, what you are after isn't addressed by this PR.

**Comment by gennadyi** [comment]
@ucg8j I see. 
This PR was referenced by https://github.com/plotly/dash-table-experiments/issues/38 as possibly solving that one. But what you are saying that it doesn't and wasn't meant to. So 38 should be reopened.

**Comment by chriddyp** [comment]
> I still can't make the table display more than 9 visible rows.

Hm, `min_height` _used_ to work. @ucg8j  - Are you aware if the original updates broke this behaviour?

**Comment by ucg8j** [comment]
`min_height` no longer works for me either - fixing this is now the priority. Apologies for the introduction of a bug. A new PR should come through in the next few days.

**Pull request merged**
